# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170716_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_page_text', models.CharField(max_length=300)),
                ('about_us_text', models.CharField(max_length=1000)),
                ('founder_image_pne', models.FileField(blank=True, null=True, upload_to=b'')),
                ('founder_desc_one', models.CharField(max_length=500)),
                ('founder_image_two', models.FileField(blank=True, null=True, upload_to=b'')),
                ('founder_desc_two', models.CharField(max_length=500)),
            ],
        ),
    ]
