# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_textmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
