# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170719_0734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
