# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170719_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglike',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='bloglike',
            name='liker',
        ),
        migrations.DeleteModel(
            name='BlogLike',
        ),
    ]
